# Generated by Django 5.1.1 on 2024-09-06 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='courseid',
        ),
        migrations.RemoveField(
            model_name='department',
            name='deptid',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='enrollmentid',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='instid',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='scheduleid',
        ),
        migrations.RemoveField(
            model_name='student',
            name='studentid',
        ),
        migrations.RemoveField(
            model_name='university',
            name='univid',
        ),
    ]
