# Generated by Django 5.1.1 on 2024-09-07 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_course_courseid_remove_department_deptid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='ClassroomNumber',
            new_name='classroomnumber',
        ),
        migrations.AddField(
            model_name='schedule',
            name='classrooms',
            field=models.ManyToManyField(to='app.classroom'),
        ),
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(to='app.course'),
        ),
    ]
