# Generated by Django 5.1.1 on 2024-09-07 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_classroomnumber_classroom_classroomnumber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Headinstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headinstructorname', models.CharField(max_length=75)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.department')),
            ],
        ),
    ]
